# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c4b31c09fe464dd593fc45711e08b35ba0e0d45d9d708c5a3e868b153ac89e3886f234161427fe03f7db0051aaf0911af574f41a0cd7ef5a76bb2c42206112d

test:
  secret_key_base: 61820b06eb64576d184d1ca672398f8e30de509411c10746b798e1180bef424a2695fac5b378127e935978b25b8e2fe597b92cefd85dbafe71fb1b43d9a0f6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
